name: Assign Azure Policy

on:
  workflow_dispatch:   # manual trigger
  push:
    branches:
      - main

jobs:
  assign-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Assign Built-in Policy
        run: |
          az policy assignment create \
            --name "storage-public-policy" \
            --display-name "Storage accounts should restrict network access-Dhina" \
            --scope "/subscriptions/d75c0c5c-debd-4cc4-b516-6f2ecb82221a" \
            --policy "/subscriptions/d75c0c5c-debd-4cc4-b516-6f2ecb82221a/providers/Microsoft.Authorization/policyDefinitions/93e4beac33dd409fab95da13" \
            --params @policy.parameters.json \
